** 一支穿云箭，千军万马来相见
*** 资料准备
**** 知乎回答
***** [# A] 链接：https://www.zhihu.com/question/20375281/answer/15088832
作者：灵执
编辑于：2012-08-14
著作权归作者所有，转载请联系作者获得授权。

第一、选一个适合你的岗位。有些太热门的岗位最好别报，几百几千人争一个岗位，难度太大。

第二、根据你的时间制定适合你自己的学习策略和计划。
1、如果你下定决心一定要考上公务员作为自己的职业，而不是被父母逼着才要考着试一下的话，那么应该遵循：＂尽可能提前、尽可能充分＂的原则做准备。

2、根据自己的长短期记忆能力、理解能力、学习习惯、身体状况制定契合自己的学习策略和计划。

3、分享一下我的复习策略和方法给你做一个参考（我是随便试试的，总共看了不超过20小时书，结果运气好考上了）：
①我考的是地方考，买了申论、行测两本书以及配套的卷子。买上以后我先用几分钟大概翻了一下两本书，了解了一下题型，然后直接做了一套行测真题卷子，是不计时的，每道题都尽量做出来，实在不会做的就直接算做错（不要随便蒙一个选项）。一共做了将近四个小时才做完。

②做完以后计算了一下每一类题（我记得好像是5类？）的错误率（做错的题数/该类型总题数），然后根据错误率从高到低安排学习顺序，也就是先学习错误率最高的题型（我计算类的题错得最多）。基本掌握以后再学习错误率第二高的题型，以此类推。这是我个人应对考试的另一个原则：＂先补短板，再建长板＂。

③然后针对具体的题型使用恰当的方法。有些题型是只要了解了、熟练了就可以掌握的，比如数列类和图表类的题，把书上的例题反复做三遍，掌握了知识和方法，基本就OK了。也有些题型是要看智商的，比如图形推理题，我只是把例题都做过一遍，就不看了，只有在别的类型的题做累了的时候才翻出来做几道挑战一下，调节状态。

④考试前一天在考试的时间做做题，比如明天上午考申论、下午考行测，那就在上午的考试时段做申论题，在下午的考试时段做行测题。（其实最好的方法是从考前一周就开始每天这样按时、计时的做题，培养出特定时段所需要的思维习惯和做题效率，不过我懒得很。）

⑤去考试的时候带了一块儿手表，考试时根据分值分配时间，做出取舍，尤其是考行测的时候，坚持一个原则：＂效率至上＂。120分钟对应120道题，也就是一分钟一道题，读完题以后没找到思路，觉得自己一分钟内做不出来的就先随便选一个（比如考智商的题），我当时是把智商题都随便图了，腾出时间检查其他题，以保证其他的题能有较高的正确率。

⑥说一下填涂，我考行测的时候是用一类题一起填涂的方法填涂答题卡的，你可以选择适合自己的方法填涂。

另外，申论的书我基本上没看，一直后悔不应该买它，买上一看我就后悔了，我觉得申论主要还是靠自己平时阅读和写作的积累。因为平时我就喜欢看书，所以对于申论题我只是看了几道书上的真题和参考答案，了解了一下题目的类型、作答方法及基本思路，就再没看了。至于申论的作文，因为申论作文基本都是议论文，我们都是从小写到大的，也没啥好说的，基本的框架如下：
第一段：破题+名言。
第二段：首先------
第三段：其次------
第四段：最后------
第五段：总结和升华+名言。
总的原则就是：首尾两段突出文采和深度，中间段落突出逻辑和严谨。再背上几句通用型的名言，比如＂海不择细流，故能成其大；山不拒细壤，方能就其高。＂这样无论写做人还是写做事都能用得上的，放在首尾两端，提分效果显著。

至于面试我就不写了，你通过笔试了再说吧。

希望你满意。

***** [# C] 链接：https://www.zhihu.com/question/20375281/answer/15505264
作者：匿名用户
发布于：2012-11-01
著作权归作者所有，转载请联系作者获得授权。

1，行政能力测试
参考书千万要扔掉！不要反复去看！否则会让你思维限定在一些条条框框之内，我好多朋友行测拿不到高分，我一看他们做题，都是这个原因造成的。其实很多人行测天生就能拿高分，只要稍微适应一下。
我那时考公务员时，在91up快学堂做了13460道题，稳居中政行测当时勤奋排行榜的榜首！你也可以去试试。
2，申论
需要申论的评分标准来写，写完在要人再给你打分。不知道申论阅卷评分的标准的话去最标准的中政申论练习。

***** [# C] 链接：https://www.zhihu.com/question/20375281/answer/14940565
作者：周淮安
发布于：2012-07-24
著作权归作者所有，转载请联系作者获得授权。国考的话，现在大部分职位需要两年工作经验，你可以首先参加年初的研究生考试（如果你想的话），在寒假就可以开始准备下半年各个省的省考。行测不难，掌握一定的技巧及把握好时间即可，至于申论，经常去图书馆看 求是，半月谈，人民日报等相关报纸杂志。另外要多写写多看人民网新闻多思考。至于用书，随便找中公或者华图的书就好啦。认真准备总结 是王道。别看考的人那么多，真正有竞争力的也就那么几个。

***** [# A] 链接：https://www.zhihu.com/question/28949010/answer/127458484
作者：申论花木君
发布于：2016-10-20
著作权归作者所有，转载请联系作者获得授权。

说明：这篇文章写于2016年上半年，内容很长，发布在花木君的微信公众号【申论花木君（xyhmls）】。虽然已经过去了几个月，但我认为有价值的文章从来不会因为时间的推移而“失色”。通过本文，多少能了解到花木君申论学习的观点、知识体系，希望大家有态度而辩证的阅读。祝好！

　花木君9年申论学习的经验

　　2万篇申论批改，9年申论学习、教学，几乎是我30岁之前全部的“关键词”。

　　9年来，我是考教师编制的学生，是申论的学习者，是申论老师，是步知公考学院的院长，是最平凡的花木君。

　　9年来，看惯了太多因方法不对而事倍功半的遗憾案例，也看到了太多所谓“名师”横行天下。申论，真的没有我们想象的那么难!今天，我想将自己对申论学习的所感、所悟、所得分享出来，希望对广大伙伴略有帮助。需要明确的是：这是个人学习、工作经验的分享，不代表权威，可喷可交流!

我眼中的申论学习

　1：申论备考，别一开始就错了

　　无论国考，还是省考，申论的普遍得分是35—55之间!

　　你会问：为嘛我越学越差?为嘛越努力分数越低?

　　其实：你的路错了，一开始就错了!

　　申论大作文一般40分，前面的几道小题60分!我们可以推断，成绩在35—55分的你，前面小题总得分只有10—35分!

　　多么恐怖、残忍的真相!所以，申论成败的关键不是作文写作，而是前面小题的得分—不能拿稳45分，及格乃至进面基本没有希望!

　花木君观点：作文是突破高分的途径，而小题才是生命线!!将70%甚至更多的精力用于小题的备考、学习，是基础一般的我们突破申论的不二法门!

　2，答题形式决定能否进面

　　有多少人距离面试只有3分以内的距离?

　　可是，小小的3分不仅注定了你失去了逆袭的机会，也提早宣布了公考失败的结果!3分，乃至再加几分真的有这么难吗?

　　坦白的讲：我们进入考场前，申论水平已经是既定的!人靠衣装，申论作答靠“形式装”试想：同样一份答卷，卷面整洁、工整的得分会高，还是缺少规划、勾勾画画的卷面高?!

我的观点是：

　　(1)前面的小题有意识的用“先总，后分”的方式，并分条理呈现，让阅卷老师扫一眼就能抓到你作答的重点、得分点。

(2)作文写作观点要明确、坦坦荡荡。一方面开篇时文章的核心观点要表达的直接、客观，不扭扭捏捏、模棱两可;另一方面分论点概括的严谨、明确，保证文章的每个段落都有一个独立的核心功能—比如第一段是引述议题、表达观点，第二段是提出分论点并论证，最后一段是结尾、升华。

(3)端庄的书写80%会赢得好感乃至加分。申论是人工阅卷，爱美之心人皆有之，阅卷老师也不例外。当然，这是申论考试，不是书法比赛，不能无限的放大书写对结果的影响，但平时就注意纸质书写、保证卷面整洁，绝对有益无害!

花木君观点：做好力所能及的小事，不仅是一种态度和修养，也是一种重要的能力，更是同一水平下能否进面的重要砝码!

　　3，逻辑衔接词是提分的神器

　　首先需要强调一下：逻辑衔接词不等于“一二三四”这种简单的罗列。

　　无论是小题还是大作文写作，其主线都是逻辑，比如综合分析题立足“论断是什么”“论断的分析和说明”“总结概述”几个核心层次来作答，申论写作围绕核心观点来加以论证、说明，这其实都是一种逻辑的表现形式。

　　几个逻辑衔接词实际上串联的就是一篇申论文章的核心思路、架构，比如“花木体”文章的常用逻辑衔接词：

　　第一段：...(背景)。然而...(引出文章的议题)。为此，我们需要...(表达文章的核心观点)。

　　第二段...(分论点一)。...问题开始凸显(分论点的缘由)。为此，需要...。同时，...促进...(措施、要求+效果)。

　　第三段：...(分论点二)。...现象突出(分论点的缘由)。为此，我们应...(措施、要求+效果)。

　　第四段：...(分论点三)。...凸显了...(分论点的缘由)。对此，需要...，让...(措施、要求+效果)。

　　第五段：...(概述)。...是...是...更是(联系社会背景，深化文章的主题)...。

　　试想，当我们掌握了这种规律和技巧，并有适当的训练、总结，在具体的考试时对材料、题目主题有了基本的认识，还会担心无从下笔?还会要花上十分钟乃至几十分钟的时间来思考文章的结构、层次吗?

花木君观点：题型是申论考察的形式，而逻辑是考试命题、呈现作答内容、展现能力的灵魂。从很大意义上来讲，申论的备考就是培养行政思维、提高逻辑分析能力。

　　4，申论写作是思维+结构+表达

　　嗯哼，这个结论很大胆，和你在任何书上看到的观点都不同，但就是这么任性，就是这么简单。

　　所谓思维，只要记住两句话：1，把自己当做公务人员来做题、写文章，不主观、不抒情;2，注重因果关系，材料反映了什么问题就分析什么问题，从哪些角度分析问题就针对性的从哪些角度来解决问题。与此同时，要注意保证前后行文流畅，不自相矛盾。

　　至于文章的结构，我认为“一个核心论点，三个(两个)分论点，五个(四个)段落”就可以。也许你会担心是否“模式化”，但我想告诉你：如果连基本的文章结构、框架都没有，那只能算流水账!

　　OK，如果你实在想在文章结构上有所创新，适当的展示一下风采、个性，那请记住一句话：保证文章“核心论点明确，分论点清楚，论据围绕论点展开”这一基本原则。

　　对于表达，不需要过于花哨，坚持“朴实、自然、客观”就可以，平时可以通过政府工作报告、人民时评、新闻联播等来积累专有词汇、句式，培养语感。

花木君观点：要提高申论写作能力，完全可以对其所要求的能力进行拆解提升，有意识的通过了解国家政策方针来培养自己的行政思维能力，通过模仿、训练来理清自己写作时固有的文章结构，通过词汇、句型、句式的积累和仿写来提升文字表达能力。

　　5，表达能力提升最好的方法是模仿和嫁接

　　都说见贤要思齐!

　　“思齐”从来就不是问题，问题的关键是怎么去“见贤”?去哪里见?毕竟这个时代，出门左转遇见“神棍”“忽悠”的可能性比遇见美女、猛男的概率还要大!

　　我的意见是“人民日报的时评文章”“伙伴们写的比较好的文章”!

　　不要问为什么只有这两处，就问问自己：有多少资料、多少书你真正的看过?!好东西、有用的东西就像讨老婆，不是越多越好，而是适合自己的、能为你所用的才是真的好!

在具体的模仿练习时，可遵循以下原则：

　　1，申论的主题会涵盖政治、经济、文化、社会、生态文明五大范畴(政治范畴的内容可不做刻意关注)，所以平时的学习中可有意识的对文章、积累的素材进行分类。

　　2，学习时，不需要整篇文章都关注，也许是一个开头，也许是一个结尾，也许仅仅只是一个排比句式，甚至只是几个词汇，请认真记下来。

　　我的态度是：没有几十页这样的笔记，那算不得认真学过申论!

　　3，结合记下的句式、词汇进行仿写、改写，部分内容可直接用到自己的写作中去。给个例子：

　　【原文】拯救和传承非物质文化遗产，要从文化安全意识着手，将民俗文化的传承纳入国民经济和社会发展的整体规划，将文化安全注入中小学的基础教育中，充分发挥非物质文化遗产对广大未成年人进行传统文化教育和爱国主义教育的重要作用，将民族文化的发扬融入生活、融入社会主义经济建设中，让其在心与心、行与行中传承。

　　【仿写】预防和治理食品安全问题，要从食品安全意识着手，将食品安全问题纳入国民经济和社会发展的整体规划，将食品安全注入中小学的基础教育中，充分发挥重大食品安全事故和食品安全识别知识在食品安全教育中的重要作用，将食品安全工作融入民众的生活、融入社会经济的建设中，将食品安全工作真正落到实处。

　　坚持一两个月后，如果你认为没有进步，那只有一个原因：你真不够用心!

花木君观点：申论的学习一如找对象，重要的不是遍地撒网，而应该是有策略、有方法、有坚持!

　　6，热点从来无需拼死拼活积累

　　申论考试会立足热点议题来展开，但务必注意，其关注的并不是热点、议题本身，而是一种思路和逻辑—客观的认识问题、辩证的(正反两面)分析问题、有效的解决问题这一能力。

　　平时的备考中，你也许花费了很多时间记住了某一个热点、问题产生的原因，但考试的材料导向会和你的记忆一样?相反，往往会让你的作答偏离材料，让你感觉无所适从、手心出汗、心烦意乱!这也是为什么存在“出考场的时候感觉良好，查分数的时候大失所望!”这一普遍现象

　　申论学习的方法、经验有很多，但罗列太多就等于没有经验。作为应试，抓住了主要方向、基本宗旨，任何难题都能迎刃而解。

花木君观点：申论是应试，重要的不是猜题，甚至不是“见多识广”，而应该是在理解国家政策、方针的基础上，能熟练的运用这种思维来分析和处理问题的能力。而掌握并不断提升这种能力，不仅能打通申论备考的“任督二脉”，对我们的生活、工作更是大有裨益!

　　关于在线备考的想法

　　从中政行测到中政申论，再到步知公考学院，我们立足网络，做过题库，做过申论批改，但最终回归到了“学习核心知识体系和方法体系的研究与创新设计”上来，坚持在特色学习方法、核心知识内容的诠释方面精耕细作。这也是为什么我辞去步知公考学院院长，而选择做一名申论老师的重要原因，因为我认为知识及教学的质量永远是衡量教师、教育机构好坏的唯一标准。在线教育的好坏、大数据的优势等等暂且不谈，我只谈谈我眼里什么才是好的在线教育模式。

1，学习氛围是备考的灵魂

　　在线学习的痛点和难点是什么?无非以下几点：

　　(1)孤独导致的闭门造车;

　　(2)自制力差导致的拖延症泛滥;

　　(3)网络的虚拟、遥远和无亲近感，让我们无法坚持;

　　(4)心理失衡导致的学习效率为0….

　　所以，我们逐步最终决定逐步放弃海量的非方案、vip用户，而专注于为方案用户、vip用户提供更具性价比的教学服务!通过微信答疑、公众号资源发布、老师社区答疑等方式让老师和伙伴、伙伴和伙伴都成为真正的朋友，相互激励、相互协助、相互竞争。也许，我们只在网络的那头，走不到你的身边，但我们决志走进你的心里，与你坦诚交流、相互学习、共同进步。

2，学习评判的标准不是“名师”，而是方法和知识体系及实操性

　　孔子算不算古往今来最牛的老师之一?他弟子三千，出了多少贤人?

　　答：72!

　　师傅领进门，修行在个人!不否认好的老师会让我们的学习事半功倍，但无限扩大乃至迷信所谓的“名师”(包括花木我本身)，完全可以定性为“耍流氓”?

　　在互联网时代，稍微用点心，资源的质量都不会太差。一次能提高成绩的备考，最关键的不是遇到了一位好的老师，而应该是一套合理的学习流程、行之有效的知识体系和方法体系，而不是将希望完全寄托在某个“老师”“专家”“秘诀”的身上。

　　所以，我坚持认为：真正好的老师，可以是为人师表的长者，更可以是与我们平等交流、相互学习的伙伴，是可以加为“微信好友”，随时联系、吐露心声的朋友!

　　花木君算不得“名师”，也不愿意成为“名师”，我只是一个申论的学习和研究者，一个对申论有属于自己独特见解的老大哥而已。

如果对公考、申论有需求或者需要切磋技巧的可以加我的个人微信号申论花木君（buzhi0938）

***** [# A] 链接：https://www.zhihu.com/question/28608943/answer/123489915
作者：一个人的战役
编辑于：2016-12-22
著作权归作者所有，转载请联系作者获得授权。

（更新）4个月国考副省级143分之备考经验
第一次更新（9月2日深夜）

2015年以应届毕业生的身份参加了国家公务员考试，准备时间4个月，买了一些辅导资料，就在学校的图书馆和自习室啃了下来，在报考比例1：2028的岗位中笔试第二，面试第一，综合成绩第一的成绩被国家部委录取。查询笔试成绩的时候，我哭了，哭得撕心裂肺。在很多人看来不可能做到的事情，我却做到了，4个月的付出也终于得到回报。现今一切尘埃落定，一切归于平静，我便顺带着回忆将这4个月的备考感受落于笔下，给后来人一些引导、一点希望和些许的鼓励。

“不登高山，不知天之高也；不临深渊，不知地之厚也”！希望各位能登高山，临深渊，而后知天高地厚。我一直很赞同，天下之事，为之，则难者亦易矣，不为，则易者亦难矣！所以，行动才有能让事情变得简单，才能让梦想有实现的可能。

一、国考考查的是什么？
先从最根本来说，我认为，国考考查的是你的管理者思维以及坚定的政治立场。
其一，管理者思维体现在，你不能再用普通民众的角度来看待社会中出现的问题，如果你想进入面试，你必须具备管理者的思维，你应该着重看到社会问题的本质，并且提出解决问题的对策和方法，你不能瞎捣乱，看到社会问题如果还依然保持在普通民众看待问题的角度，那么你不会得到高分的。这具体表现在，行测中，常识的一些选项设计需要管理者的大局观、言语理解中大部分题目正确选项是对策；申论中，你需要对材料进行加工的默认遵循的潜规则是你要具备管理者的思维，你的文章写作看起来是一个很好的管理者。所以，加入公务员考试的大军，你的思维必须开始转变成为管理者思维，像管理者一样去思考。这里，最为简单的一个例子便是，普通人看新闻联播觉得新闻空洞无力，而你在看新闻联播的时候你会发现，当你听到加强社会主义核心价值观的教育的时候，你不觉得那是空洞无力，因为你知道当前很多社会问题的出现部分原因是民众偏离主流价值观，传统道德的缺失，信仰的缺位，所以有必要加强社会主义核心价值观的教育，帮助大家重新确立良好的道德信仰。当你看新闻能够看到这样的时候，你已经开始具备管理者的思维了。
其二，坚定的政治立场体现在，国家管理者是一个集团，你的立场必须站在集团内部，也可以说即便你不是党员，你也要尊重党，要站在党的立场，你所有的态度和观点都必须维护国家和党的利益，当然这并不意味着你要说假话，而只是意味着你看待问题必须理性，态度更应该是倾向于党和国家。具体表现在，行测考试中，常识题中的有利于树立国家形象和政府形象的选项往往是对的，言语理解中涉及对国家政府的用词必须把握有度，政府错了，你用词需要轻一点，比如：指责，而不能用斥责、苛责和谴责，然而如果是敌对国如日本错了，那么毫不犹豫要斥责、苛责和谴责，资料分析中的综合题，通过政府管理体现出越来越好的选项往往是正确选项。申论中，你的言语倾向也必须维护国家和政府的形象，你可以提出对策和建议，但是你的对策和建议是要建立在保有政府地位和形象的提前下。这些在后期你的训练中，必须慢慢去培养。
若从具体说来，行测和申论的各个小模块考查的侧重点均有所不同，在这方面，很多经验贴和教科书都写的非常的详细，我便不再累述。比如，申论考查阅读理解能力，综合分析能力，提出问题和解决问题的能力，文字表达能力等等。国考的副省级和地市级考试还微微有些区别，但是区别不是太大，副省级更多考查的是理论能力，而地市级更多考查贯彻执行能力，这是因为副省级作为更高的管理者当然必须有理论基础，而地市级你更多去贯彻执行就可以了，理论并没有显得那么重要。


二、国考要考多少分才能进入面试？整体如何规划？
国考一般职位在130分（行测要过线60分）就可以进入面试，而要做到考130分，那么暂定一个目标就是行测要考70分，申论要考70分。行测通过备考学习训练，一般情况下考65分是没有太大问题，申论的话70分也是挺好争取的。具体，行测的常识20个题目要做对13道，言语理解40个题要做对32个，数量关系15个题要做对7个题目，蒙剩下8个题（俗称做7蒙8），逻辑判断40个题目做对32个题目，资料分析20个题目争取全部都对。申论，前面4个题目争取拿到80%的分数即48分，后面大作文一般争取在二类文即20-25分。把这样的目标定好之后，接下来就是分模块进行各个突破。

如果将学习分为四个阶段：
第一个阶段就是掌握基础的知识，对每个知识点和考前进行全面覆盖的复习，掌握每种题型的解题技巧。这个阶段就是对公务员考试的基础常考的题型进行全面的复习和掌握，为后期提高做题速度夯实基础。很多人都说要提高做题速度，但是如何提高做题速度，很多人说要大量做题。但是，我想说，大量做题是无效的，大量做题的前提是你打下了很好的基础，大量做题才有意义，如果你只是为了做题而做题，那么做再多的题目也是没有作用的。如果把基础打扎实的，看到题目能立马辨识出是哪种类型的题目，这种类型的题目用什么方法和技巧能自动反应过来，你在做题的时候能带动应用做题技巧和方法，以及知识点的回顾，这个时候做题才成体现出你意义和价值，如此反复训练，上了考察自然能够秒杀，自然能够提供做题速度，而正确率又不会因为你的速度受到影响。

第二个阶段，进行模块练习，这是对第一个阶段的查缺补漏，同时也是更加了解和清楚自己的长短的阶段，之所以要了解自己的长短处，是因为：第一，对于自己优势的模块要牢牢把握不能丢分数，另外还要加强这个模块的练习，压缩时间给短处的模块。第二，对于自己真心不会的题型能够在考场上面马上识别出来，然后一看到这种题型，直接跳过。很多人都在经验贴中提出要放弃，但是并没有人告诉你们要如何放弃，必须经历这个过程，你才知道怎样放弃，如果你没有掌握这个技能，往往在考场上你花了一分钟才发现这是你不会的题目，那么这个时候你放弃已然没有任何的意义。第三，对整个考试才会有一个整体的格局感，那些真正裸考的人是不可能做到格局感的，而裸考真正能上岸的一万个里面很难找到一个，格局感让你能对整个考试有个全局的掌控，如果考场上突然哪个模块出题非常难了，你可以进行全局的调整，就像我考这次，言语理解阅读量增加了，那些没有格局感的人做了一个小时的言语理解，那么整个做题的计划就完全乱了。那些说裸考上岸的，请万万不要相信他们的谎言，他们不过是为了证明自己很厉害，装作没有努力，靠天资聪颖就考上了，其实都是谎言！

第三个阶段，开始整套题的进行训练。各个模块研究透了之后就是将这些模块组合起来，找到整体的感觉以及各个模块的做题顺序。对近5年的真题反复做5遍以上。每次做题的方法和顺序都可以有所调整，不断尝试，找到最适合自己的方法和技巧。这个阶段会有一个比较质的提升，前提是前面两个阶段都打好基础了。对套题进行训练的时候，开始严格控制时间，提高做题速度，这个阶段求速度才显得有意义，也才有现实的可能性。

第四个阶段，做全真的模拟训练。这个阶段是根据市面上的一些模拟试卷，进行找做题的感觉，因为真题做过几次之后会很有熟悉感，所以在考前2周可以做一些模拟题，第一，这为了上考场的时候不会因为一看题目好陌生而慌乱阵脚，第二，有些热门的预测具有一定的参考性，尤其是申论热点的预测，有时候是可以贴近的，特别是大作文，通过预测卷去背一些基础素材是很有必要的。

具体的每个阶段的学习任务和时间的安排因人而异，这里简单的规划，供大家参考和借鉴。第一个阶段，8月初到9月中旬，为期40天；第二个阶段，9月中旬到10月中旬，为期30天；第三个阶段，10月中旬到11月中旬，为期30天；第四个阶段，11月中旬到考试（预测11月25号），为期15天。各个阶段的任务安排大家可以根据自己的情况来设定，但是大部分该复习的知识点我想还是必须要复习的。如果大家希望我在这方面多提供一些建议的话，那么可以在告诉我，点点赞同，或者在评论区里表达下需求，如果确实很多人都需要的话，那么我后期抽空对这方面的进行全面的扩充。

三、国考行测各模块备考方法
1、常识部分。常识的考察，一般是政治2道（这个可以在10月下旬再集中复习记忆），经济1道，这掌握基础经济常识就可以应对，人文13道，这是注重对中国传统文化的考察的，尤其现在更是提倡对重新温习传统文化，所以在这方面前提复习把遇到的题目的知识点全部掌握，如果有空那就把一些这方面的书籍当做小说随便看看即可，最主要的还是要在做题中来学习，科技4道，科技部分有着很强的原则技巧和方法，牢牢掌握这些技巧和方法，这4道题一般都能够拿下里。而法律部分一般为了不让法学专业的学生占据优势，不会怎么出题，部分地方的省考会出题，考省考的同学要认真复习法律知识，复习过程中本着善良平等正义的精神来把握学习，找到这样的感觉到去选选项一般也都是对的。
很多人认为常识很难，其实只要找到做题的方法原则以及技巧，并没有想象中那么难，题做多了，多加总结，方法和技巧也自然显现出来。我总结了一些方法和技巧，但是因为笔记被朋友借走了，还么有换回来，后面还给我了，我再将笔记中一些重要的点补充上来，供大家参考。另外，常识万万不能花很多时间去复习，这是一个积累的过程，优先把握原则和方法，在这基础上再适当去学习，补充一些基础知识，专门花很多时间去复习不会有多好的效果的。因此，谨记，掌握原则技巧，以做题中遇到的知识点为补充，平时如阅读小说那样去看看一些参考书就好了。

2、言语理解。（9月2日深夜更新）
其一，内容选自哪里？

言语理解的内容选摘自《人民日报 》、《新华网》、《半月谈》、《三联生活周刊》等一些刊物，因此平时要有时间多读读这些刊物，不仅是培养管理者思维，积累申论素材的有效手段，同时也可以提高阅读速度，训练阅读技巧。在2016年的国考中，言语理解阅读量突然增加让很多人没有如正常那般去做试卷，很多人言语做了一个小时，资料分析基本蒙了，因此平时必须大量去阅读，提高阅读速度，同时在阅读中培养速读技巧和阅读技巧。文段的阅读技巧性非常强，大量做题后自然能感觉得出来。速读技巧及训练，在此先留空，赞同票数超过1000票后就来补充写上。阅读技巧是可以通过教材和做题显现的，而我在速读技巧及训练则是很少人提及的。我一般能在25分钟内做完40道言语理解（更快的时候可以在20分钟），一般人需要用35-40分钟，这样在时间上我比别人多了10-15分钟的优势。这我想应该归功于我的速读技巧，那些反应阅读速读很慢的学弟学妹可以关注一下，后期我将着重分享这方面的一些感受。

其二，哪些题型是重点？

言语理解中判断阅读需要着重抓的题型是主旨概括题，意图判断题和细节阅读题，做好这三种题型，其他题型自然迎刃而解。因此在前期的训练中最重要的是把握这三种题型，在后期的学习中也应该每天各做5道这样的题型，其他题型不过是这三种题型的延伸和变向而已。而逻辑填空注重实词和成语的考查，大量掌握词汇与成语是学习重点。

其三，如何练习与提高分数？

片段阅读：第一，应该进行小题型的分类学习，学习基础的知识，然后大量做分类的小题型题目，将所学的基础知识（包括关联词阅读法+行文脉络阅读法）反复训练。第二，小模块进行强化训练，将所学的知识杂糅在整个小模块中，要看到题目的时候迅速反应出是属于哪种小题型，然后不自觉地将各种小题型的做题方式和技巧准确运用在做题当中。如某题目一看题目马上断定是主旨概括题，这时候四个选项主体不一，立马使用主体一致法，迅速找出文中的主体，然后看选项选主体一致的选项，核对无误即刻完事，这样一道题目也就在20-30秒就迅速做完了。如果没有经过系统训练的人看题加读选项就要用掉20-30秒，而时间就是在这样前期系统学习，后期强化训练中争取来的，所谓，熟能生巧便是这样的道理吧。

逻辑填空：第一，基础模块的学习。第二，大量的做练习。从练习中掌握出题方式和答题技巧，尤其要注意使用提示法，一般文段中往往都会有一些提示词来提示，要在不断做题中找到提示词，然后迅速选出选项来。

其四，其他需要交代的话。

（1）每种小题型的读题方式都是有所不同的，有些题型是直接看设问，然后看文段，最后看选项，我们称之为213，而有些题目的阅读是需要先看设问，然后看选项，最后再看文段，我们称之为231，不同的题型决定不同的读题顺序，最佳读题顺序能够帮你争取到分秒的时间，每道题如果能节约5秒，20到判断阅读能节约将近两分钟。所以读题的顺序也是如此之重要，不容小觑。

（2）关联词阅读法，必须在阅读中尤其注重关联词的把握，把握关联词的意义在于能够将文段中很多信息进行略读，只读最重要的文句就可以选出答案。那么关联词阅读法在基础学习中也应该扎实训练与学习。

（3）行文脉络阅读法，这是从宏观方面来把握整个文段的行文脉络，总分总，分总，总分，分总分，分分，等几种行文脉络的把握也是快速做题的关键，如该题目是总分结构，那么主旨意图题则只需看总句，分句就可以略读了。

所有的时间的有效利用都是在平时培养正确的高效的阅读习惯中取得的，因此，学习基础知识，模块训练，到整套题的训练是一个循序渐进的过程，急不急，欲速则不达，前期应该扎实基础，后期才能突飞猛进。切忌不可一上来就整套题进行训练，这样的做题时没有任何效果的。


3、数量关系。（9月2日深夜更新）

有足够复习时间的同学这块是不能轻易放弃的，这个模块一般都可以做7到题蒙8道题。在前期的学习中都应该全方位进行学习，在学习过程中应该知道哪些题是自己能够掌握的，而哪些题则自己无论如何无法掌握的，那么在考试中看到自己的菜速度摘走，不是自己的菜就直接放弃。前期的学习就在于区分哪些是自己的，哪些不是自己的。知己知彼，百战不殆。如果在考场上还花时间在区分哪种菜属于自己的时候，那么这个模块大概也就付之东流了，可以休矣。

所以，如果还有3个月以上复习时间的同学，建议千万不能放弃这个模块，而不足三个月的同学则因人而异，数学好的同学，务必拿下，数学不好的同学把这个模块放到最后来复习，有能力就抓，没有能力就坚决弃之。所谓，食之无味，弃之可惜，说的大概就是不足3个月备考的同学了吧。另外，如果有充足复习的同学万万不能把数量关系放在最后的十五分钟来做，那个时候自己的心态已经相当急躁了，适合做的题目是常识判断或类比推理这种题目不会因为急躁而影响做题的正确率和正常思考的能力。（做题模块的顺序以及博弈的技巧之后会专门补充说明。）

有超过3个月复习时间的同学，第一步学习基础的公式，第二步，学习速算技巧，第三步，模块练习。第四步，找到属于自己的菜，放弃不属于自己的菜。做7蒙8。


4、判断推理。（待补充）

5、资料分析。（待补充）



四、国考申论备考方法（待补充）




五、备考学习资料的选择（9月2日深夜更新，这个部分很多学弟学妹关系，便优先更新，今天只是粗略更新，后期会不断精细化）。
1、行测书推荐。

（1）超过三个月复习时间的同学：

中公的专项训练或者华图模块宝典或者粉笔腰果一些机构的模块书+1000题+历年真题+部分和国考一致的省市真题+前人的学习笔记（论坛可以去找，或者用致远先绅整理的笔记），市面上基本都大同小异，找其中一套来学习即可。

（2）时间毕竟短的同学：

中公或华图的行测教材+国考历年真题+部分和国考较为一致的省市真题+前人学习笔记（论坛找，或者用致远先绅整理的笔记）


2、申论书推荐

《人民日报》评论+华图或中公或粉笔或腰果的申论教材+历年真题+前人学习笔记（论坛找，或者用致远先绅整理的笔记）


3、视频辅助资料推荐

视频资料其实各个机构都有，华图中公粉笔腰果等等机构都有视频资料，还有讲义，用该机构的讲义配合视频资料听课进行学习。视频资料可以自己到论坛去找，如果比较有经济实力想要支持正版去各个机构的官网购买也是可以。当然，我和我身边的小伙伴们一般都是找致远先绅买（微信为zhiyuanxianshen），他的视频资料非常全面。但是，我不是很赞同把大部分时间用来看视频，毕竟自己做题自己总结，自己消化，然后再做题才是根本，因此在使用致远的资料的时候，并不是要全部用，只需要选一些适合自己的就可以了。不要花太多时间去看视频，视频只是带你进入学习状态，全面复习一遍，而之后自己静心做题消化，自己思考总结，如此反复，才是比较有效的学习方式，可以避免浪费时间。

关于各个机构的老师的推荐（后期更新细化）


4、学习计划制定推荐
在我看来，国考的复习分为三个核心阶段，第一个阶段为基础知识的学习，第二阶段为模块练习，第三个阶段是套题演练。那么这三个阶段在时间上的安排和学习任务的制定上，以及具体用书和用资料的安排上，都应该科学安排，循序渐进，学习过程本身就是循序渐进，不可违背学习个规律，步步为营。

因此，我认为可以制定一个学习规划，将各个阶段的学习任务安排好，然后稳扎稳打，稳步推进。

六、国考报名职位选择方法（会在报名之前更新）

七、与面试相关（出成绩之前更新）

写此文已经是深夜，熬不住了，先睡了，后期我再慢慢补充吧，如果此文对大家有用，那么希望不要吝惜你的赞同票噢，大家的鼓励是我不断书写的动力！晚安~

2016年9月2日 凌晨3点30分。


--------------------------------------------------

各位好，最近年底，忙到哭，实在没有时间一一回复微信和私信，如果需要备考资料可以咨询致远先绅（微信号：zhiyuanxianshen）祝大家考试顺利！
忙过这一阵，我会继续更新的，谢谢大家的关注！ 

***** [# B] 链接：https://www.zhihu.com/question/49832333/answer/120669389
作者：黑化肥发灰
编辑于：2016-09-06 
著作权归作者所有，转载请联系作者获得授权。

考过十次，进面四次，省厅以上三次，上岸两次。最后一次上岸是笔试面试双第一。省考，国考，选调生，政法干警，法检单招都考过。行测国考最高拿过73，面试最高拿过91。所以我觉得自己还是有发言权的。

行测看初高中基础，这个短期无法提升，除非你下决心去高三复习班坐一年。简单技巧就是把该做的做完，做不出的或者耗时太久的放弃。保证会做的内容的正确率达到99%。拿到卷子先做资料分析，这个最耗时（一般我用25分钟），但是答案其实很简单，很多人都忽略了。数量分析大家一般正确率都不行，或者太耗时间，个人经验只做前两个简单的，后面全部放弃，哪怕蒙个全b全c也比自己耗时间写划算。省下的时间用到资料分析或者图形，收益率大的多。写一道涂一个卡，别最后一起图，浪费时间不说还容易图错。

申论看字体。内容再辣鸡都不怕，改卷子的不是什么机关老笔杆子，一群屁都不懂的在读研究僧而已。你字体写的漂亮，特别是一笔漂亮的行楷，铁定高分。辅导机构教你的各种套路基本上都是扯淡的。有那功夫不如练练字。有闲功夫可以看看学习出版社出版和人民出版社联合出版，每年一本的《理论热点面对面》系列丛书开开思路，看最近三年的即可。某宝有售，注意出版单位，别买了辅导机构的辣鸡山寨版就行。尽量用钢笔，略粗的答题，字相对会好看点。当然，笔要买好点的，顺滑最重要，有利于答题速度。

***** [# A] 链接：https://www.zhihu.com/question/49832333/answer/134213526
作者：赵特立
发布于：2016-12-04
著作权归作者所有，转载请联系作者获得授权。

第二、多做多练，保证时间
在这里，给自己准备公考的朋友一个我的备考三步法，可能对有的考生不太合适，只做交流，欢迎理性批评。
一是找私人公培、报班、看视频，具体效果我认为如同这个先后顺序，先不说找私人公培和报班，这个在后边的第三块：接受指导、学习技巧里还会讲到，具体的学法也有老师辅导，不再专门介绍，这里重点说一下如何看视频。我觉得某公、某图的网课都不错，但是，我个人倾向某图的视频，可能是看的多吧，不是说某公的不好，只是，看的比较少。具体的步骤是，先把讲义打印出来，自己先做一遍，会做的，把思路记下来，不会的在题前边做个标记，然后听视频上老师讲，对于不懂的或者重要的，要反复的重放，把题吃透，对于自己会做的，要认真的与老师的思路对照，在对照中进步。然后过段时间，回头再做一遍题，再用同样的方法，然后再做一遍……至少三遍，多者不限。
二是看书，看书的话，也是一样的，先自己做，然后写思路，做标记，现在市面上很多书都不错，按模块、题型等，分的很细。
三是做套题，按照国、联、省－5、4、3的原则，就是国考题找最近五年的，联考题找最近四年的，各省的省考题最近三年的，把这些真题找齐了，一天一套，按照考试时间，上午行测，下午申论，晚上复习，按照这么一个安排，考前认真的做上十天二十天的套题，做题的时候，关手机、关电视、关好门，最好找个自习室，图书馆，事实证明，在家很难学进去。完全仿真的环境，按要求的时间做，最后统计错题率。
以上这三个方面及其包含的内容，就是我建议的两个备考三步法。
第一个，是学习三步法：听老师讲、看视频，是通经络，打下基础，开发你的思维；看书，是练套路，学习一下招式，让你会动手；做套题，是实战训练，让你练习怎么动手击中对手。
第二个，是做题三步法：先预习，自己做，无论会与不会，做对与做错，这是基础；再看答案，老师讲的，或者书上的参考答案，与自己的思路进行对照，在对照中产生碰撞，在碰撞中得到提升；最后复习，根据之前的对照，结合生理记忆曲线，三天小复习，七天大复习，考前总复习。
结合这两个三步法，通过这大量的做题，多做多练，再加上足够的时间保证：一天，至少应该5个小时，考前半个月左右，做套题的时候，至少应该8小时，这些，就是你执行力的一个体现。
有考生问我：我时间很少，怎么办？我问他，你时间很少是多少？他说，大约一个小时吧。我说，那么这一个小时你利用上了吗？他很不好意思的挠了挠头。还有考生说：老师，我上班远，天天光公交车来回就得两个小时。我说：你在公交车上做什么？他愣了。然后我说：刷陌陌、微信、QQ，或者看电子书，对不对？他说：是啊，大家都这样啊。我说：是啊，大家都在玩，你可以学习，正因为大家都在玩，你才更有可能考上。
其实，咱们的时间不是没有，而是，没有被利用：你等公交车，可以记至少一个成语；你上了公交车，至少可以听两节视频课；你到了家，泡脚的时候，至少可以读两遍人民日报评论员文章……最后，我愉快的告诉大家一个小秘密，刚才我说的，95%以上的人是做不到的，所以，如果你努力一下，成为那5%的人，你就离成功近了一大步，这一步有多大？呵呵，很大。不过，我觉得，你有95%的可能性不会按我说的做，微信、陌陌、电子书，应该还是大家的最爱。

第三、接受指导，学习技巧
接受指导，有这么两个方法：私人公培和报班
先说一下私人公培，比如我，干这个也有几年了，多少有点发言权。这种一般是在职的公务员，工作之余，或因为面子，或是亲戚关系，当然，也有收取一些费用的，这些公务员，单科水平可能一般，但是，你如果能把他的东西学到手，再加上你原本比他强的一些部分，那么，你就能超越他，所以，你上岸的希望，至少比他当年要高一些，正所谓没有状元师父，只有状元徒弟。如果你身边有在职的公务员，能跟着一块学习，效果是最好的，因为这种一对一的辅导，对方有足够的精力教你。我当时带我亲友家小孩备考的时候，他们有的甚至吃住在我家，我一下班就陪他们学习，我一上班，他们就做我留下的作业；而且全部是实战经验，不仅是考试的实战经验，还有复习的实战经验，我一直认为我的备考笔记，比一些教材要好一些，因为很有实用性。当然，最好是有一定难度的岗位的公务员，你别找考上那些报名总人数不超过10个人的岗位，这种岗位的考试难度之小，实在不好一提，考上这种岗位的公务员的水平，也不能说不强，但是，具体视情况而定吧，还是找一些，至少也得是正常一些的岗位上的公务员，能找到部委的大神，当然最好了。
如果没有这种条件，那么看你的实际情况，比如经济条件、决心等，如果仅从效果来考虑的话，个人感觉还是报个班比较好，市面上培训班也不少，怎么选呢，相对而言，我自荐我们的职业公考模式，具体看一下这个地方准备考公务员，笔试究竟要不要报班？ - 赵特立的回答 - 知乎。
可能大家觉得，我在做广告为自己做宣传。如果这么认为，我也不否认，但是我想申明，公道自在心中，我的身份，我的工作，与你无关，与你有关的，仅仅是你的备考。你的关注点在哪里，你的成就就在哪里。正如同样是在看穹顶之下，有人看到了环保的重要意义，有人在八卦柴静的私生活。没办法，中国人多，各种各样的人都有，这到也是好事，越多的人关注我的身份，关注我是不是在做广告，那么，你就越容易考上，因为，那些人注定不是你的对手。
刚才提到报班好，并非因为我的工作，而是有以下几点原因，第一，职业的老师，水平毕竟比你强一点，肯定能学到东西，第二，你花了钱，心情上肯定会不一样，你花50块钱买的书，不一定看，但是，你花5000块钱报的班，你一定会认真的学，第三，在课堂上，有互动，可以与老师交流，老师也会了解到你的缺点，对你进行调整，至少我带的几个考生，我都是有针对性的对他们进行弥补。


第三、关于申论的学习

很多人不知道申论怎么学，下面我再专门就申论介绍一下方法。除了刚才提到的两个三步法之外，申论有它的特殊性，所以备考的话，还要加上三个“字”：第一、练字；第二、写字；第三、拍字。
第一、练字。我觉得这个是最重要的，我认识一些申论强人，我们经常一块交流，我发现，我跟他们聊的思路也好，方法也好，技巧也好，都差不多，但是，我们的申论分数能差十到二十分，我觉得，有一个重要的原因就是字，我的字，实不相瞒，谁来跟我比我都不怕，因为我肯定没你写的好。我一直觉得，我的申论很受字体的影响。最早的时候，12年，我有一个学生，当时我的申论考的也不好，所以也没怎么教她，这小姑娘也没怎么学，但是，她的字特别好看，后来山东省考，申论得了70整！虽然没有上岸，继续努力，在原有申论的基础上，我教了她一些概括题的思路和基本方法，然后她第二次的时候国考上岸。总之，如果你想提高申论，练字是第一步，也是最最最重要的。
第二、写字。写字，就是作题，这个题怎么做，你就怎么写，一定要写，一定一定要写！怎么写？方法的话，是按咱们的两个三步法，但是，具体操作下来的时候，你一定一定，一定一定要在完全仿真的环境下写，定好时间，不能超时，也尽量不要错时，就是说，一般申论是下午两点到四点半或者五点，你也尽量按这个时间；同时，打印好正式的申论纸，而且张数不能有任何的差错，你别打印N张，写错了就再换一张——你在考场上老师会给你无限量的提供纸张？门也没有！所以，你也老老实实的只用规定的纸张。别问我写错了怎么办，也别问我能不能涂改——你在考场上是怎么处理的，你这里就怎么处理，明白吗，高仿真的实战环境！就像你练习打拳，你天天打沙袋，不去实战，你就不会得到最快的进步。很多考生练申论，如同看评书，老师讲完了，这边觉得不错，回头没什么事了，不写不练，永远不能提升！所以，你一定一定，一定一定要写！
第三、拍字。拍字？你没看错，就是拍字，怎么拍？用手机，用相机拍。拍那玩意干什么？传给老师给你批改，当然，如果你能见到老师，让老师给你当场点评，那效果是也不错，这两个方法各有特色吧。但是，相对于当场点评，我还是喜欢拍字，当然，也不一定非得要拍下来，你复印一份给老师送过去也行啊，大家能理解就行，千万别钻牛角尖。之所以这样，是因为申论很复杂，比如我吧，面对学生传过来的申论题，我会认真的批改，对于一些难一些的题，我会发给我的几位同行老师，一起进行批改，争取把最好的答案回馈给学生。等于花费大量的精力和时间，来帮你哪怕提升一点点，但是，我一直觉得，这一点点，对你而言，可能比较重要！包括我在讲课的时候，我喜欢学生问我问题，但是，我不喜欢当场回答，一是有可能不会，这个可能性很小，但是也存在，我不否认，我也知道，我不可能会所有的公考题；二是，我一直觉得，有些题目，最好是进行一个完全的解析和思考，甚至与同行进行一个深入的交流，才可以把思路拿出来告诉学生，这是对学生负责，这样的效果会比较好，尤其是对于申论，我多想十分钟，有可能思路就会更好一些，我觉得这个才是最主要的。所以，找一个负责的老师，你给他拍个字发过去，然后听取一下他的点评，我觉得对你的提升，效果非常好。
大家可能都有印象，很多武侠片，主角掉到一个山崖里，结果发现了一本无敌的秘芨、宝典，然后看着书就练成什么神功、剑法，出去后如何如何，这都是小说情节。在公考里，尤其是申论，你看书，一开始多少有点进步，但是，如果想真正的进步，还是得练，还是得下笔，要练字，要写字，要拍字，否则，你就算是有了宝典，哪怕自宫，也未必练成神功。同学们，这三个“字”非常重要，大家要定要按照这个方法来提升申论的成绩，一定要练字，一定要写字，一定要拍字！一定一定要！ 我们的学生，申论都写了至少四十篇，每一篇写两到三遍，加起来是100多次的申论实战模拟

***** [# B] 链接：https://www.zhihu.com/question/40400563/answer/88413331
作者：张旭
发布于：2016-02-28
著作权归作者所有，转载请联系作者获得授权。

谢邀。

　　其实题主你眼前的纠结和心里的担忧其实都是正常，最近不止一人跟我交流，说复习没有头绪，说备考没有信心，说学习没有动力，说改变没有勇气，其实我明白你的意思，你只是还没有找到属于自己的备考方式，还没有确定自己向前一步该走的是那条路。下面的内容没有煽情，没有吐糟，没有励志故事，没有传销式的口号，也暂不谈解题技巧，就只谈正确的备考思路和踏踏实实的复习方法。不要把公考看得那么难那么复杂，其实每个人智商都差不太多，上岸的人也大都是寻常智力，两个月的时间，不走弯路，行测70+是正常的水准，而且我也相信，聪明努力如你，看完这篇文章会静下心来重新审视自己的复习。

一、行测思想。拿到你该拿的分，一分都不要浪费。

　　什么是你该拿的分，就是通过短期高效的复习和练习，你能拿到的分数。直接地说，就是言语，判断推理，资料分析这三大块。拿好了这个三大块的分，你的分数就绝对不会低于70分，而且性价比极高，难度上也是人人都可以掌握的。言语就是考你的阅读理解表达能力和语文的初级应用，判断推理就是考逻辑学的初级原理，资料分析就是考你的简单的数学计算和统计学的基本应用。并且都是有迹可以寻的，出题人还没有达到创造题目的水平，都是这些框架内出题的，因为这几部分很少有难题怪题，谁都可以通过扎实掌握知识点之后拿到一个很高的准确率，85%-90%的准确率通过系统的复习是完全可以达到的， 甚至更高。当你做到了这一点，70分的行测分就是你的起步分，如果你稳定地达了这个水平，在这基础上你还有时间来复习数量关系这一块，把这一块的正答率再做到80%，行测80分就也不是什么难事。

　　再分析一下其他题型，常识，只要是现代人，就是靠自己的生活经验，也会有60%的正确率，并且分值也低，如果有精力按模块扫一眼公基，70%的正答率也不难。数量关系呢，再怎么差都会一题吧?其它都选B或C，总会有两三题的正解吧?如果全部都做完，不会低于用半个小时来做吧，对个七八题很高了吧?差别在哪里?我舍弃了几分，换来的就是二三十分钟的宝贵时间，把这些时间放在资料分 析上，正确率会低吗?这就是得高分的关键。所以说，根据你自己的掌握情况，先把常识和数量搁置，放到最后面来复习，拿到你该拿的分，一分都不要丢，你的分数就不会低，也不会迷茫于原地踏步。当然，有的同学天资比较高，复习时间充足，在数量关系上拿分多一点，就更好了，行测分数就很有希望8字头。

二、教材和资料。只利用，不依赖，学方法，长本事。

　　为了避免有广告嫌疑，就统称某机构，反正大家心知肚明，目前公考教材比较好的来来去去就那么几家，并且各个机构的教材结构和内容都是大同小异。淘宝上一搜一大把。是分模块复习，共五本，内容详细，各题型列举的很全面，是一套可以用的教材，也就这一套教材就足够了，因为我们主要通过它来了解，我们面对的究竟是什么。

　　怎么用这个教材呢，就跟着教材一个模块一个模块地走，不要自以为是地东翻西翻，一步一步地往下走，把每个题型都踏实地掌握了，行测也就基本上能把握住了。为什么这么说呢，这举个例子让大家好理解，比如学车，教练教你起步，跟你说扎上安全带，检查空档，点火，挂档，放手刹，放离合，加油门。方法都跟你说，你也很清楚，是不是你就会了呢?不可能的，还是需要你亲自一次次地去实践，多开多练，练多了就形成了你的本能反应，也就掌握了起步的方法了。

　　先学理论再去通过实践巩固，最后再形成属于自己的理论，这些我们从小用到大的应试方法还算是科学好用的，当然这是对于自学能力强的考生而言的，毕竟现在没有拿着教鞭站在身后跃跃欲试想要管你的老师了。而常见的教材也有不足就是，有些解析并不是特别的负责任，我们都知道，很多答案里的“显而易见”往往都不是那么的显而易见，所以永远不要完全地去依赖教材，它只是在给你提供难题，怎么解决还是要靠自己。多动脑，多思考，多总结，方法和理论掌握不对，做再多的题也是徒劳。

三、做题。题目不在多，而在于精，我们所追求的是一个题目做出四个题目的效果。

　　做题，行测里重中之重。刚才说了，你知道了原理和方法，是要通过练习做题来掌握的，而教材里的习题往往是不够的，不足以让你达到炉火纯青的境界。我这里给大家强调一下，不仅要把题目作对，还要掌握解题的规律，当你做对一道题，掌握一类题。这样你的认识就上升到一定高度。这个时候，你在进入考场的时候，就是会当凌绝顶，一领众山小的感觉，不会再是懵懵懂懂的，这个时候，你离笔试考试成功也就不远了！

　　 再次强调一下，适量做题是必要的，千万不要进行题海战术。模拟题和真题的质量差距不是一点，而且模拟题不少也有错误。当时候会误导你。有人说，国考真题太少不够练习怎么办？还有一个途径，那就是各省省考真题。虽然质量比国考要逊色一些，但是也是很好的复习资料。比所谓的点题、押题不知道要强上百倍。

　　还有我想说的是，你做过的或许比你还未经历的更重要，现在你需要去回顾自己的所有对与不对，而不是继续漫无目的地刷题做题。学习一些常用的技巧，通过做题总结出解题的方法和思路，再运用回我们解题的过程中，这才是做题的意义。不仅是公基和行测需要这样做，你的写作也是。有了想法和思路，列出提纲再完成文章，这只是完成了练习的一半，再回过头来反思和总结为什么这样写，怎么样才可以写的更好，再从自己写的文章里抽出自己的逻辑和观点，才算是完成了一篇合格的文章。简单来说，就是你想要做好一件事，你必须先学习和思考做这件事的方法，再用最好的方法去指导自己做成这件事，然后再做同类事情的时候能最快最好的做成它。

　　另外就是做题速度，复习的时候千万不要追求速度，就认认真真去做就行了，速度这个东西，你熟练了，速度自然上来，千万不要本末倒置，这也是很多同学的复习的误区，白白给自己无谓的干扰。

四、套题和做题顺序。适合自己的，就是最好的。

　　套题，其实不是那么重要 考前十天八天每天做一套就行了，目的就是为了让你对整体做题的感觉有所了解。顺序呢，我觉得这样做是最科学的，先易后难，由浅入深。常识-言语-判断-资 料-数量。常识用5到8分钟搞定，言语30分钟，判断35分钟，数量把一眼会做的做了，不会的果断蒙B或C，把剩下的时间都拿来做资料吧，时间会很充足的，不会说做不完。填答题卡，一定要养成习惯做完一大块就填一块，千万不要放在最后一起涂，如果做完题了，发现没时间填答题卡，真的叫欲哭无泪，基本每次考试都听说有在考场里下跪的考生!手表，一定带上一块，不要电子表，就要普通那种指针的表，不是每个考场都有钟给你看的。

五、复习心态。复习多用心，备考不功利。

　　这个真是不懂怎么说，其实说白了， 能不能考上，就看你的决心和恒心。有这个决心，强烈的渴望，哪怕人笨点，方法不怎么对头，弯路多走了点，一样是可以成功的。

　　但是很遗憾的是，很多同学往往就是没有背水一战的决心和水滴石穿的恒心，一天到晚在网上求大神指教，QQ上装模作样弄点习题一起做，美其名日：共同进步!复习不到几分钟，就摸个手机上个微信，上个QQ，发个短信，猪朋狗友来个电话去酒吧，去旅游，去逛街，得了，明天再复习也不迟;每天得过且过，考公不是自己的想法，是父母让考的，安心地做考碗族，啃老族，借考公务员的名义逃避现实，玩的时候意气风发，生龙活虎，一摸书就头晕眼花，心烦意乱，还不断地问别人为什么，让别人可怜;一天到晚 借口没时间，工作忙，应酬多;还有的热衷于参加这个班那个班，看这个视频那个视频，就喜欢听别人讲，就是不肯拿起笔和草稿纸自己用心去做一做题，有的一天到晚在网上看什么励志文章，喝点心灵鸡汤，感动得一塌胡涂，信心犹如打了鸡血了一样，下定了很大的决心，发毒誓一定要考上，一回过头复习，还是老样 子，KTV里唱得最深情那个就是他，酒桌上最出风头还是他，旅游的途中最亮丽的身影还是他。诸如此类，你觉得得你能考上的话这个世界还有天理吗?我们讲劳逸结合，效率提高，但是起码你要先劳一下呀，累一下呀。欢迎各位同学对号入座，如果还有没提到的情况请自行反省。

　　再就是不要有太强的功利心，每天想着我有多少多少对手，他们复习的怎么样了，我会考什么样的名次，我是不是基本就没有机会了，其实这除了浪费你宝贵的时间和精力外，其他一点意义都没有，不如踏实下心来，想昨天看过的书和接下来该好好研究的题，调整好自己学习的心态，就算这次运气不好没有上岸，也要保证下一次不再翻开书就又只剩下两个月了，好吗？

　　好了，关于行测的话已经说尽，一条笔直的平坦的路是给你了，无论情不情愿你都已经走上了它，辞不辞职，报不报班都不如你的决心重要，所以，向前吧，勇敢点儿。

*** 规划
**** 目前的雏形
***** 以模块展开细分
****** 行测
******* TODO 1.不计时，尽最大可能的独立完成一套国考真题卷
请记录下时间、感觉，并进行归纳和总结。。。

******* TODO 2. [0%] 根据第一步的结果安排学习计划，原则：先补短板，再建长板
基本掌握了错误率最高的题型再学习错误率第二高的题型，以此类推

- [ ] 数量关系 [0/2]
  - [ ] 数字推理
  - [ ] 数学运算
- [ ] 言语理解与表达 [0/3]
  - [ ] 选词填空
  - [ ] 语句表达
  - [ ] 阅读理解
- [ ] 判断推理 [0/3]
  - [ ] 事件排序
  - [ ] 图形推理
  - [ ] 演绎推理
- [ ] 资料分析 [0/3]
  - [ ] 文字型
  - [ ] 图形型
  - [ ] 表格型
- [ ] 公共基础知识 [0/6]
  - [ ] 马克思主义及其在当代中国的发展
  - [ ] 法律
  - [ ] 社会主义市场经济
  - [ ] 行政管理
  - [ ] 公文写作
  - [ ] 国情及时事热点

****** 申论
***** 在时间轴开展
*** 公考的记录
**** 日记向天天记
**** 书本学习进度
**** 以事件为线索
***** 头发是大家的
loading...
***** 选择的时间和钢笔的关系
loading...
**** 对公考的领悟
**** 对生活的感悟
**** 拾人牙慧备忘
* end
